export const GET_INCOMING_DATA_SUCCESS = 'GET_INCOMING_DATA_SUCCESS';
export const GET_INCOMING_DATA_SUCCESS_RSI = 'GET_INCOMING_DATA_SUCCESS_RSI';
export const GET_INCOMING_DATA_FAILURE = 'GET_INCOMING_DATA_FAILURE';