export const GET_INCOMING_DATA_SUCCESS = 'GET_INCOMING_DATA_SUCCESS';
export const GET_INCOMING_DATA_SUCCESS_RSI = 'GET_INCOMING_DATA_SUCCESS_RSI';
export const SET_DATE_RANGE_SUCCESS = 'SET_DATE_RANGE_SUCCESS';
export const GET_INCOMING_DATA_FAILURE = 'GET_INCOMING_DATA_FAILURE';
export const SET_ACTIVE_INDICATORS = 'SET_ACTIVE_INDICATORS';