export const GET_INCOMING_DATA_REQUEST = 'stats/GET_INCOMING_DATA_REQUEST';
export const GET_INCOMING_DATA_SUCCESS = 'stats/GET_INCOMING_DATA_SUCCESS';
export const GET_INCOMING_DATA_FAILURE = 'stats/GET_INCOMING_DATA_FAILURE';
